services:
  closure-db:
    image: postgres:18
    ports:
      - "${CLOSURE_POSTGRES_PORT:-54326}:5432"
    environment:
      POSTGRES_DB: closure_local
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - closure-pgdata:/var/lib/postgresql
  closure-redis:
    image: redis:8-alpine
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - "${CLOSURE_REDIS_PORT:-63796}:6379"

volumes:
  closure-pgdata:
