services:
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rts_local
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
